name: Daily Stock Price Prediction

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day

jobs:
  predict_stock_price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib tensorflow scikit-learn openpyxl
      - name: Run prediction script
        run: python predict.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update Excel file'
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          file_pattern: 'predicted_prices.xlsx'
  
