name: Daily Stock Price Prediction

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day

jobs:
  predict_stock_price:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib tensorflow scikit-learn openpyxl
      - name: Run prediction script
        run: python predict.py
      - name: Commit and push changes

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'updated xls'

          branch: ${{ github.ref }}

          commit_options: '--no-verify'
  
      
  
